### ISSUE TITLE
Numerous Errors after "Run"

### ISSUE THREAD

**Issue by tommysteryy** [Nesvilab/FragPipe-Analyst-doc#17] opened 2023-11-08 07:18 UTC
Hello Fragpipe team!

We were trying to analyze some data in `https://fragpipe-analyst.org/`, so we uploaded our `combined_proteins.tsv` and `experiment_annotations.tsv` and pressed run, and this is what showed on the UI:

![Screen Shot 2023-11-07 at 7 41 26 PM](https://github.com/Nesvilab/FragPipe-Analyst/assets/55601970/3d31ee06-aadc-48df-b2d4-eea40e11861d)

If you need, I can provide the two `.tsv` files we uploaded (they're rather big so I haven't included them here yet).

Not sure if this is helpful, but another thing that consistently happened to us was when we used the `dev` server http://fragpipe-analyst.nesvilab.org/, with the same `.tsv` files, we ran into many of the errors that others have raised issues for on this repo (but did not respond lol). The error message we got was: `"An error has occurred. Check your logs or contact the app author for clarification."`

Thanks in advance!

**Comment by mshag21** [comment] 2023-12-12 08:41
I am too facing the same issue, can somebody help

**Comment by hsiaoyi0504** [comment] 2023-12-12 15:57
@tommysteryy @mshag21 Could you send me your files to reproduce the issue? yihsiao@umich.edu. And probably at least post your experiment_annotation.tsv here. It's hard to reproduce things based on these information.

**Comment by hsiaoyi0504** [comment] 2023-12-12 15:59
I think most people raised the issue before then it turns out the input file has some errors. Thanks.

**Comment by hsiaoyi0504** [comment] 2024-01-14 00:07
Closing since no followup.

**Closed as completed by hsiaoyi0504** 2024-01-14 00:07 UTC
