### ISSUE TITLE
Website not available

### ISSUE THREAD

**Issue by fedefratini** [Nesvilab/FragPipe-Analyst-doc#25] opened 2024-03-11 10:11 UTC
Since last week, i can't work on http://fragpipe-analyst.nesvilab.org/
the website connection fails

what's the problem?

thanks

Federica

**Comment by hsiaoyi0504** [comment] 2024-03-15 01:00
@fedefratini Are you still not able to access? It works for me and couldn't reproduce what you mentioned.

**Comment by fedefratini** [comment] 2024-03-15 12:06
now, it works, but only sometime I'm able to download the report and I can't understand why: I run 2 very similar analysis (same condition, number of sample, quite the same number of proteins, same threshold and analysis settings) but in one case a get the report, in the other case it just open a new blank window. Rarely I can download the report, can you tell me why? thank you

**Comment by hsiaoyi0504** [comment] 2024-03-15 17:20
@fedefratini If it's inconsistent behavior, I doubt it's more related to your local network. Try to use other network. I couldn't get you much support if you or I can't always reproduce. I will close this for now, but feel free to follow up with me an email about your data yihsiao@umich.edu.

**Closed as completed by hsiaoyi0504** 2024-03-15 17:20 UTC
